### PR TITLE
Seed database

### PR DESCRIPTION
**Pull request by saeed79darvish**

### CODE REVIEW

**Comment by saeed79darvish** [comment]
@aku2nnya  I've updated my project to use the Airbnb style, please take a look!

**Comment by saeed79darvish** [comment]
@Jvenci   I've updated my project to use the Airbnb style, please take a look!

**Comment by saeed79darvish** [comment]
@RamKhalsa   I've updated my project to use the Airbnb style, please take a look!

**Comment by saeed79darvish** [comment]
@MarissaShieh   I've updated my project to use the Airbnb style, please take a look!

**Comment by saeed79darvish** [comment]
@saeed79darvish   I've updated my project to use the Airbnb style, please take a look!

**Comment by MarissaShieh** [comment]
Hi @saeed79darvish! It looks good.

One recommendation is to put 'bundle.js' into a .gitignore file because that will become very big as the project grows. It is also not necessary to include because it is generated anytime anyone runs webpack on your code.

Looking forward to seeing your API GET path and your fake generated data!

**Review by MarissaShieh — APPROVED** [review]
Hi @saeed79darvish! It looks good.

One recommendation is to put 'bundle.js' into a .gitignore file because that will become very big as the project grows. It is also not necessary to include because it is generated anytime anyone runs webpack on your code.

Looking forward to seeing your API GET path and your fake generated data!

**Pull request merged**
